### ISSUE TITLE
Master Issue

### ISSUE THREAD

**Issue by will-r-wang** [davidaarmstrong/daviz#6]
### 1. A cleaned up version of the JS code that leverages that D3 library.
- [x] sigd3.default (Closed by: #7)
- [x] sigd3.mcmc (Closed by: #10)
- [ ] sigd3h.default
- [ ] sigd3h.mcmc

### 2. An R package that utilizes the code in the R2D3 framework.
- [x] sigd3.default (Closed by: #7)
- [x] sigd3.mcmc (Closed by: #10)
- [ ] sigd3h.default
- [ ] sigd3h.mcmc

cc @davidaarmstrong
